global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
    
    # Warning alerts - grouped notification
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'default'
    # Webhook to log alerts (for demo)
    webhook_configs:
      - url: 'http://api:8000/webhooks/alerts'
        send_resolved: true

  - name: 'critical-alerts'
    # Slack webhook (add your Slack webhook URL)
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#alerts-critical'
    #     title: 'Critical Alert: {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    
    webhook_configs:
      - url: 'http://api:8000/webhooks/alerts'
        send_resolved: true

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://api:8000/webhooks/alerts'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'component']