global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mlops-churn-prediction'

# Alertmanager configuration (optional for now)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files (we'll add alerting rules later)
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application metrics
  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 10s

  # MLflow metrics (if exposed)
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    scrape_interval: 30s

  # Prefect metrics (if exposed)
  - job_name: 'prefect'
    static_configs:
      - targets: ['prefect:4200']
    scrape_interval: 30s