global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mlops-churn-prediction'

# Rule files
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration (we'll set this up next)
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      timeout: 10s

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 10s

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    scrape_interval: 30s

  - job_name: 'prefect'
    static_configs:
      - targets: ['prefect:4200']
    scrape_interval: 30s